### ISSUE TITLE
bug: dependabot is bypassing some of the pipeline checks

### ISSUE THREAD

**Issue by sbates** [slalombuild/secureli#124] opened 2023-06-12 22:56 UTC
Dependabot's independent branch naming is causing it to skip some of the pipeline checks

**Comment by tdurk93** [comment] 2024-01-18 18:26
I reviewed a dependabot PR and it ran the same checks as other PRs, and ran the same set of checks upon merge. Closing this ticket since I can't reproduce this issue.

**Closed by tdurk93** 2024-01-18 18:26 UTC
Labels: bug
